// /src/components/quest-landing/sections/FaqSection.tsx
'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, X } from 'lucide-react';

interface FaqSectionProps {
  className?: string;
}

interface FaqItem {
  question: string;
  answer: string;
}

// const faqs: FaqItem[] = [
//   {
//     question: "Who is Quest?",
//     answer: "I am the key that unlocks the door to your subconscious mind.\n\nThe Questions I ask are designed in-house after extensive primary and secondary research on human behavior and sociology. I use agentic AI architecture using reasoning models and large proprietary knowledgebase  on your responses to figure out the story behind the surface. "
//   },
//   {
//     question: "Who is this test for?",
//     answer: "This is for you if you want to understand:\n\n1. Your Untapped Potential\n2. What makes you unique.\n3. How the world sees you.\n\nand don't want to\n\n1. Pay for therapy.\n2. Live clueless about your psychology."
//   },
//   {
//     question: "Is the test free?",
//     answer: "The test is completely free.\n\nI will give you a summary report free of cost after analyzing your responses. If you like the summary, you can download the 35+ page PDF report generated by extensive analysis methods, which also incorporates your feedback to the free report."
//   },
//   {
//     question: "How to maximize my benefit from this diagnosis?",
//     answer: "Follow these guidelines while answering questions:\n\n1. Give more context - More details you provide, More accurate my analysis will become.\n\n2. Fill your responses like you are chatting with a close friend - This will give me a better understanding of you\n\n3. Be honest - People tend to respond like the person they want to become, but not how they truly are. This makes it difficult for me to analyse you properly\n\n4. Take your time - Don't rush through questions. Try to be accurate but also try to finish it in one sitting."
//   },
//   {
//     question: "Is this a personality test?",
//     answer: "I am not a typical personality test. Personality tests restrict you in boxes, compare you with an average statistic, doesn't allow you to give context, give complete details or reasons behind your answers.\n\nYou're not a statistic.\nYou're a story.\n\nThat's why I do things differently."
//   },
//   {
//     question: "Is my personal information secure?",
//     answer: "100%. Your identity is safe and secure. You can even stay anonymous while giving the test."
//   }
// ];

const faqs: FaqItem[] = [
  {
    question: "What is the Quest Private Intelligence File?",
    answer: "Quest is a private, aesthetic Internal Architecture file created from your own words. It is a digital intelligence artifact—a record that reveals the Internal Reality of your mind through a highly composed, formatted layout."
  },
  {
    question: "Why does this resonate with High-Intent Thinkers?",
    answer: "Unlike generic tools, Quest serves as a personal \"mirror file\" that captures your psyche in words, providing validation that your complexity makes sense. It is designed for those who crave Depth and Clarity, seeing identity as a personal project rather than a casual interest."
  },
  {
    question: "How is the file curated?",
    answer: "The file is built entirely from your language. By decoding your responses to open-ended thought provoking questions, your word choices, your tone, thinking depth, even linguistic emotional patterns etc. we gather the raw material that is then processed through our internal system and formatted into a deep behavioral blueprint of your patterns, contradictions, and mental structures."
  },
  {
    question: "How does the system identify Blind Spots?",
    answer: "The system scans over 600 psychological traits to identify the primary load-bearing elements of your personality. It synthesizes isolated traits into active \"Behavioral Physics,\" documenting how you generate energy and dissolve friction under pressure."
  },
  {
    question: "What is the logic of the Resonance Hash?",
    answer: "The Resonance Hash [PACE]-[INPUT]-[DRIVE]-[FUEL] is a psycho-metric configuration derived from your specific Quest Mask. It acts as a \"Server Specification\" for your Internal Processing system, used to calculate social compatibility and Behavioral Loops."
  },
  {
    question: "What is a Quest Mask?",
    answer: "Your architecture is categorized into one of 32 unique archetypes (Masks) organized into 6 primary clusters. The system identifies your Identity Triad—the specific combination of your Internal Driver (SELF), External Signal (WORLD), and Growth Trajectory (ASPIRE)."
  },
  {
    question: "How do I access my specific psych file? ",
    answer: "You may begin the observation process to view a free fragment of your file with a visible aesthetic layout. Once the patterns are synthesized, you may unseal the remainder and receive your full, confidential edition."
  },
  {
    question: "How to maximize my benefit from this Quest?",
    answer: "Follow these guidelines while answering questions:\n\n1. Give more context - More details you provide, More accurate my analysis will become.\n\n2. Fill your responses like you are chatting with a close friend - This will give me a better understanding of you\n\n3. Be honest - People tend to respond like the person they want to become, but not how they truly are. This makes it difficult for me to analyse you properly\n\n4. Take your time - Don't rush through questions. Try to be accurate but also try to finish it in one sitting."
  },
  {
    question: "What layers are documented in the full configuration?",
    answer: "The complete confidential file is a multi-layered archive:\n\n• The 'Unsaid' Dictionary: Decrypts your Internal Reality, translating defense mechanisms into their protective roots.\n\n• Evolutionary Origins: Reframes modern struggles—like Overthinking—as successful ancient survival strategies.\n\n• The Behavioral Circuit: Maps your recursive Behavior Loops, exposing the \"Synthetic Relief\" you seek and the \"Systemic Tax\" it costs.\n\n• The Social Translator: A practical cheat sheet to help others navigate your Thinking Patterns and energy ledger.\n\n• There are many more layers like Resonance Index (your life philosophies, character doppelgangers, growth levers, make your own AI journaling companion, etc."
  },
  {
    question: "Is this a permanent record?",
    answer: "Yes. Quest is an object of ownership—a private artifact that you can save, revisit, and preserve as a documented asset of your Self-Understanding."
  },
  {
    question: "Is my personal information secure?",
    answer: "100%. Your identity is safe and secure. You can even stay anonymous while giving the test."
  }
];

const FaqSection: React.FC<FaqSectionProps> = ({ 
  className = '' 
}) => {
  const [openIndex, setOpenIndex] = useState<number | null>(0); // First item open by default

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section 
      className={`w-full min-h-screen max-w-5xl mx-auto px-6 py-12 container ${className}`}
    >
      {/* FAQ Title */}
      <div className="mb-12">
        <h2 
          className="text-black mb-8 font-gilroy-medium text-[40px] text-center"
        >
          Frequently Asked Questions
        </h2>
      </div>

      {/* FAQ Items */}
      <div className="space-y-0">
        {faqs.map((faq, index) => (
          <div key={index} className="border-b border-white/20">
            {/* Question */}
            <button
              onClick={() => toggleFaq(index)}
              className="w-full py-6 flex items-center justify-between text-left hover:bg-white/5 transition-colors duration-200"
            >
              <h3 
                className="text-black pr-4 font-gilroy-regular text-[28px] font-weight-400"
                style={{ lineHeight: '105%', letterSpacing: '0%' }}
              >
                {faq.question}
              </h3>
              
              {/* Expand/Collapse Icon */}
              <motion.div
                animate={{ rotate: openIndex === index ? 45 : 0 }}
                transition={{ duration: 0.3, ease: "easeInOut" }}
                className="flex-shrink-0 w-8 h-8 flex items-center justify-center"
              >
                {openIndex === index ? (
                  <X size={24} className="text-white rotate-45" />
                ) : (
                  <Plus size={24} className="text-white" />
                )}
              </motion.div>
            </button>

            {/* Answer */}
            <AnimatePresence>
              {openIndex === index && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                  className="overflow-hidden"
                >
                  <div className="pb-6 pr-12">
                    <p 
                      className="text-black whitespace-pre-line font-gilroy-regular"
                      style={{
                        fontWeight: 400,
                        fontSize: '20px',
                        lineHeight: '130%',
                        letterSpacing: '0%'
                      }}
                    >
                      {faq.answer}
                    </p>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        ))}
      </div>
    </section>
  );
};

export default FaqSection;
